version: '3.8'

services:
  postgres-user:
    image: postgres:13
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    networks:
      - banking-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres-user
    networks:
      - banking-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-user:5432/userdb

  postgres-account:
    image: postgres:13
    container_name: postgres-account
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accountdb
    ports:
      - "5434:5432"
    networks:
      - banking-net

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8002:8000"
    depends_on:
      - postgres-account
    networks:
      - banking-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-account:5432/accountdb

  postgres-transaction:
    image: postgres:13
    container_name: postgres-transaction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactiondb
    ports:
      - "5435:5432"
    networks:
      - banking-net

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8003:8000"
    depends_on:
      - postgres-transaction
    networks:
      - banking-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-transaction:5432/transactiondb

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@banking.com
        PGADMIN_DEFAULT_PASSWORD: admin123
      ports:
        - "5050:80"
      networks:
        - banking-net

networks:
  banking-net:
    driver: bridge
